version: "3.8"

services:
  mongodb:
    image: mongo:7.0.9
    restart: always
    volumes:
      - mongodb-data:/data/db
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  bot:
    build: .
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  mongodb-data:
